# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Quinielas.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Quinielas(object):
    def setupUi(self, Quinielas):
        Quinielas.setObjectName("Quinielas")
        Quinielas.resize(622, 445)
        self.centralwidget = QtWidgets.QWidget(Quinielas)
        self.centralwidget.setObjectName("centralwidget")
        self.tabAgregarysupuestos = QtWidgets.QTabWidget(self.centralwidget)
        self.tabAgregarysupuestos.setGeometry(QtCore.QRect(10, 10, 601, 381))
        self.tabAgregarysupuestos.setObjectName("tabAgregarysupuestos")
        self.Agregar = QtWidgets.QWidget()
        self.Agregar.setObjectName("Agregar")
        self.tabAgregar = QtWidgets.QTabWidget(self.Agregar)
        self.tabAgregar.setGeometry(QtCore.QRect(10, 10, 541, 331))
        self.tabAgregar.setObjectName("tabAgregar")
        self.Jugador = QtWidgets.QWidget()
        self.Jugador.setObjectName("Jugador")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.Jugador)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 331, 221))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.idjugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.idjugador.setObjectName("idjugador")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idjugador)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nombrejugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.nombrejugador.setObjectName("nombrejugador")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombrejugador)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.apellidojugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.apellidojugador.setObjectName("apellidojugador")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.apellidojugador)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.edadjugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.edadjugador.setObjectName("edadjugador")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edadjugador)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.posicionjugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.posicionjugador.setObjectName("posicionjugador")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.posicionjugador)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.pesojugador = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.pesojugador.setObjectName("pesojugador")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pesojugador)
        self.btnAgregarJugador = QtWidgets.QPushButton(self.Jugador)
        self.btnAgregarJugador.setGeometry(QtCore.QRect(370, 20, 131, 27))
        self.btnAgregarJugador.setObjectName("btnAgregarJugador")
        self.btneliminarjugador = QtWidgets.QPushButton(self.Jugador)
        self.btneliminarjugador.setGeometry(QtCore.QRect(360, 130, 131, 27))
        self.btneliminarjugador.setObjectName("btneliminarjugador")
        self.btnmodificarjugador = QtWidgets.QPushButton(self.Jugador)
        self.btnmodificarjugador.setGeometry(QtCore.QRect(360, 80, 141, 27))
        self.btnmodificarjugador.setObjectName("btnmodificarjugador")
        self.tabAgregar.addTab(self.Jugador, "")
        self.Entrenador = QtWidgets.QWidget()
        self.Entrenador.setObjectName("Entrenador")
        self.formLayoutWidget = QtWidgets.QWidget(self.Entrenador)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.identrenador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.identrenador.setObjectName("identrenador")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.identrenador)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.nombreentrenador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nombreentrenador.setObjectName("nombreentrenador")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombreentrenador)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.apellidoentrenador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.apellidoentrenador.setObjectName("apellidoentrenador")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.apellidoentrenador)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.edadentrenador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.edadentrenador.setObjectName("edadentrenador")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edadentrenador)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.pesoentrenador = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pesoentrenador.setObjectName("pesoentrenador")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pesoentrenador)
        self.btnAgregarEntrenador = QtWidgets.QPushButton(self.Entrenador)
        self.btnAgregarEntrenador.setGeometry(QtCore.QRect(360, 20, 161, 27))
        self.btnAgregarEntrenador.setObjectName("btnAgregarEntrenador")
        self.btneliminarentrenador = QtWidgets.QPushButton(self.Entrenador)
        self.btneliminarentrenador.setGeometry(QtCore.QRect(370, 150, 151, 27))
        self.btneliminarentrenador.setObjectName("btneliminarentrenador")
        self.btnmodificarentrenador = QtWidgets.QPushButton(self.Entrenador)
        self.btnmodificarentrenador.setGeometry(QtCore.QRect(360, 90, 161, 27))
        self.btnmodificarentrenador.setObjectName("btnmodificarentrenador")
        self.tabAgregar.addTab(self.Entrenador, "")
        self.Arbitro = QtWidgets.QWidget()
        self.Arbitro.setObjectName("Arbitro")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.Arbitro)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 341, 211))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.idarbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.idarbitro.setObjectName("idarbitro")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idarbitro)
        self.nombrearbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nombrearbitro.setObjectName("nombrearbitro")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombrearbitro)
        self.apellidoarbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.apellidoarbitro.setObjectName("apellidoarbitro")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.apellidoarbitro)
        self.edadarbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edadarbitro.setObjectName("edadarbitro")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edadarbitro)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.pesoarbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.pesoarbitro.setObjectName("pesoarbitro")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pesoarbitro)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.posicionarbitro = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.posicionarbitro.setObjectName("posicionarbitro")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.posicionarbitro)
        self.btnAgregarArbitro = QtWidgets.QPushButton(self.Arbitro)
        self.btnAgregarArbitro.setGeometry(QtCore.QRect(370, 20, 141, 27))
        self.btnAgregarArbitro.setObjectName("btnAgregarArbitro")
        self.btneliminararbitro = QtWidgets.QPushButton(self.Arbitro)
        self.btneliminararbitro.setGeometry(QtCore.QRect(360, 150, 131, 27))
        self.btneliminararbitro.setObjectName("btneliminararbitro")
        self.btnmodificararbitro = QtWidgets.QPushButton(self.Arbitro)
        self.btnmodificararbitro.setGeometry(QtCore.QRect(370, 80, 131, 27))
        self.btnmodificararbitro.setObjectName("btnmodificararbitro")
        self.tabAgregar.addTab(self.Arbitro, "")
        self.Clubes = QtWidgets.QWidget()
        self.Clubes.setObjectName("Clubes")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.Clubes)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 411, 91))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.nombreclub = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.nombreclub.setObjectName("nombreclub")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombreclub)
        self.idclub = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.idclub.setObjectName("idclub")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idclub)
        self.btnAgregarClub = QtWidgets.QPushButton(self.Clubes)
        self.btnAgregarClub.setGeometry(QtCore.QRect(30, 140, 99, 27))
        self.btnAgregarClub.setObjectName("btnAgregarClub")
        self.btneliminarclub = QtWidgets.QPushButton(self.Clubes)
        self.btneliminarclub.setGeometry(QtCore.QRect(30, 240, 99, 27))
        self.btneliminarclub.setObjectName("btneliminarclub")
        self.btnmodificarclub = QtWidgets.QPushButton(self.Clubes)
        self.btnmodificarclub.setGeometry(QtCore.QRect(20, 190, 111, 27))
        self.btnmodificarclub.setObjectName("btnmodificarclub")
        self.tabAgregar.addTab(self.Clubes, "")
        self.Equipo = QtWidgets.QWidget()
        self.Equipo.setObjectName("Equipo")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.Equipo)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 391, 211))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.idequipo = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.idequipo.setObjectName("idequipo")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idequipo)
        self.nombreequipo = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.nombreequipo.setObjectName("nombreequipo")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombreequipo)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.txtEquipoEntrenador = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtEquipoEntrenador.setObjectName("txtEquipoEntrenador")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtEquipoEntrenador)
        self.txtEquipoJugadores = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtEquipoJugadores.setObjectName("txtEquipoJugadores")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtEquipoJugadores)
        self.txtEquipoClub = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtEquipoClub.setObjectName("txtEquipoClub")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtEquipoClub)
        self.btnAgregarEquipo = QtWidgets.QPushButton(self.Equipo)
        self.btnAgregarEquipo.setGeometry(QtCore.QRect(40, 230, 151, 27))
        self.btnAgregarEquipo.setObjectName("btnAgregarEquipo")
        self.btneliminarequipo = QtWidgets.QPushButton(self.Equipo)
        self.btneliminarequipo.setGeometry(QtCore.QRect(220, 230, 131, 27))
        self.btneliminarequipo.setObjectName("btneliminarequipo")
        self.btnmodificarequipo = QtWidgets.QPushButton(self.Equipo)
        self.btnmodificarequipo.setGeometry(QtCore.QRect(380, 230, 131, 27))
        self.btnmodificarequipo.setObjectName("btnmodificarequipo")
        self.tabAgregar.addTab(self.Equipo, "")
        self.Temporada = QtWidgets.QWidget()
        self.Temporada.setObjectName("Temporada")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.Temporada)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 361, 121))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.iniciotemporada = QtWidgets.QDateEdit(self.formLayoutWidget_8)
        self.iniciotemporada.setDate(QtCore.QDate(2018, 11, 22))
        self.iniciotemporada.setObjectName("iniciotemporada")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iniciotemporada)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_22.setObjectName("label_22")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.finaltemporada = QtWidgets.QDateEdit(self.formLayoutWidget_8)
        self.finaltemporada.setDate(QtCore.QDate(2018, 11, 22))
        self.finaltemporada.setObjectName("finaltemporada")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.finaltemporada)
        self.idtemporada = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.idtemporada.setObjectName("idtemporada")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.idtemporada)
        self.btnAgregarTemporada = QtWidgets.QPushButton(self.Temporada)
        self.btnAgregarTemporada.setGeometry(QtCore.QRect(40, 170, 171, 27))
        self.btnAgregarTemporada.setObjectName("btnAgregarTemporada")
        self.label_28 = QtWidgets.QLabel(self.Temporada)
        self.label_28.setGeometry(QtCore.QRect(10, 80, 149, 27))
        self.label_28.setObjectName("label_28")
        self.tabAgregar.addTab(self.Temporada, "")
        self.Jornadas = QtWidgets.QWidget()
        self.Jornadas.setObjectName("Jornadas")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.Jornadas)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 10, 361, 121))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.idjornada = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.idjornada.setObjectName("idjornada")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idjornada)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.dateJornada = QtWidgets.QDateEdit(self.formLayoutWidget_6)
        self.dateJornada.setDate(QtCore.QDate(2018, 11, 22))
        self.dateJornada.setObjectName("dateJornada")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateJornada)
        self.btnAgregarJornada = QtWidgets.QPushButton(self.Jornadas)
        self.btnAgregarJornada.setGeometry(QtCore.QRect(30, 150, 132, 27))
        self.btnAgregarJornada.setObjectName("btnAgregarJornada")
        self.tabAgregar.addTab(self.Jornadas, "")
        self.tabAgregarysupuestos.addTab(self.Agregar, "")
        self.Supuestos = QtWidgets.QWidget()
        self.Supuestos.setObjectName("Supuestos")
        self.tabEventos = QtWidgets.QTabWidget(self.Supuestos)
        self.tabEventos.setGeometry(QtCore.QRect(2, 9, 601, 341))
        self.tabEventos.setObjectName("tabEventos")
        self.Encuentro = QtWidgets.QWidget()
        self.Encuentro.setObjectName("Encuentro")
        self.label_25 = QtWidgets.QLabel(self.Encuentro)
        self.label_25.setGeometry(QtCore.QRect(271, 50, 20, 20))
        self.label_25.setLineWidth(7)
        self.label_25.setMidLineWidth(1)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.Encuentro)
        self.label_26.setGeometry(QtCore.QRect(60, 10, 68, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.Encuentro)
        self.label_27.setGeometry(QtCore.QRect(440, 10, 68, 17))
        self.label_27.setObjectName("label_27")
        self.btnAgregarEncuentro = QtWidgets.QPushButton(self.Encuentro)
        self.btnAgregarEncuentro.setGeometry(QtCore.QRect(390, 120, 171, 27))
        self.btnAgregarEncuentro.setObjectName("btnAgregarEncuentro")
        self.label_29 = QtWidgets.QLabel(self.Encuentro)
        self.label_29.setGeometry(QtCore.QRect(30, 90, 131, 17))
        self.label_29.setObjectName("label_29")
        self.txtEncuentroE1 = QtWidgets.QLineEdit(self.Encuentro)
        self.txtEncuentroE1.setGeometry(QtCore.QRect(10, 40, 181, 27))
        self.txtEncuentroE1.setObjectName("txtEncuentroE1")
        self.txtEncuentroE2 = QtWidgets.QLineEdit(self.Encuentro)
        self.txtEncuentroE2.setGeometry(QtCore.QRect(390, 40, 181, 27))
        self.txtEncuentroE2.setObjectName("txtEncuentroE2")
        self.txtEncuentroEncuentro = QtWidgets.QLineEdit(self.Encuentro)
        self.txtEncuentroEncuentro.setGeometry(QtCore.QRect(10, 120, 181, 27))
        self.txtEncuentroEncuentro.setObjectName("txtEncuentroEncuentro")
        self.tabEventos.addTab(self.Encuentro, "")
        self.Biorritmos = QtWidgets.QWidget()
        self.Biorritmos.setObjectName("Biorritmos")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.Biorritmos)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 391, 81))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_30.setObjectName("label_30")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_34.setObjectName("label_34")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.txtBiorritmoTipo = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtBiorritmoTipo.setObjectName("txtBiorritmoTipo")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtBiorritmoTipo)
        self.txtBiorritmoPersona = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.txtBiorritmoPersona.setObjectName("txtBiorritmoPersona")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtBiorritmoPersona)
        self.label_35 = QtWidgets.QLabel(self.Biorritmos)
        self.label_35.setGeometry(QtCore.QRect(10, 120, 101, 17))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.Biorritmos)
        self.label_36.setGeometry(QtCore.QRect(230, 120, 101, 17))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.Biorritmos)
        self.label_37.setGeometry(QtCore.QRect(420, 120, 101, 17))
        self.label_37.setObjectName("label_37")
        self.biorritmointelectual = QtWidgets.QLineEdit(self.Biorritmos)
        self.biorritmointelectual.setGeometry(QtCore.QRect(0, 150, 141, 27))
        self.biorritmointelectual.setObjectName("biorritmointelectual")
        self.biorritmofisico = QtWidgets.QLineEdit(self.Biorritmos)
        self.biorritmofisico.setGeometry(QtCore.QRect(200, 150, 141, 27))
        self.biorritmofisico.setObjectName("biorritmofisico")
        self.biorritmoemocional = QtWidgets.QLineEdit(self.Biorritmos)
        self.biorritmoemocional.setGeometry(QtCore.QRect(400, 150, 141, 27))
        self.biorritmoemocional.setObjectName("biorritmoemocional")
        self.btnBiorritmo = QtWidgets.QPushButton(self.Biorritmos)
        self.btnBiorritmo.setGeometry(QtCore.QRect(430, 40, 121, 27))
        self.btnBiorritmo.setObjectName("btnBiorritmo")
        self.tabEventos.addTab(self.Biorritmos, "")
        self.Quinielas = QtWidgets.QWidget()
        self.Quinielas.setObjectName("Quinielas")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.Quinielas)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(30, 30, 401, 111))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_38.setObjectName("label_38")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_39.setObjectName("label_39")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_40.setObjectName("label_40")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.txtQuinierlas = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtQuinierlas.setObjectName("txtQuinierlas")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtQuinierlas)
        self.txtQuinielasJornada = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtQuinielasJornada.setObjectName("txtQuinielasJornada")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtQuinielasJornada)
        self.txtQuinielasEncuentro = QtWidgets.QLineEdit(self.formLayoutWidget_9)
        self.txtQuinielasEncuentro.setObjectName("txtQuinielasEncuentro")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtQuinielasEncuentro)
        self.btnhacerapuestas = QtWidgets.QPushButton(self.Quinielas)
        self.btnhacerapuestas.setGeometry(QtCore.QRect(120, 180, 141, 27))
        self.btnhacerapuestas.setObjectName("btnhacerapuestas")
        self.tabEventos.addTab(self.Quinielas, "")
        self.Historial = QtWidgets.QWidget()
        self.Historial.setObjectName("Historial")
        self.tablaestimulaciones = QtWidgets.QTableWidget(self.Historial)
        self.tablaestimulaciones.setGeometry(QtCore.QRect(30, 40, 256, 192))
        self.tablaestimulaciones.setObjectName("tablaestimulaciones")
        self.tablaestimulaciones.setColumnCount(0)
        self.tablaestimulaciones.setRowCount(0)
        self.tablaresultados = QtWidgets.QTableWidget(self.Historial)
        self.tablaresultados.setGeometry(QtCore.QRect(320, 40, 256, 192))
        self.tablaresultados.setColumnCount(3)
        self.tablaresultados.setObjectName("tablaresultados")
        self.tablaresultados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaresultados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaresultados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaresultados.setHorizontalHeaderItem(2, item)
        self.tabEventos.addTab(self.Historial, "")
        self.tabAgregarysupuestos.addTab(self.Supuestos, "")
        Quinielas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Quinielas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 25))
        self.menubar.setObjectName("menubar")
        Quinielas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Quinielas)
        self.statusbar.setObjectName("statusbar")
        Quinielas.setStatusBar(self.statusbar)

        self.retranslateUi(Quinielas)
        self.tabAgregarysupuestos.setCurrentIndex(1)
        self.tabAgregar.setCurrentIndex(6)
        self.tabEventos.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Quinielas)

    def retranslateUi(self, Quinielas):
        _translate = QtCore.QCoreApplication.translate
        Quinielas.setWindowTitle(_translate("Quinielas", "MainWindow"))
        self.label.setText(_translate("Quinielas", "ID"))
        self.label_2.setText(_translate("Quinielas", "Nombre"))
        self.label_3.setText(_translate("Quinielas", "Apellido"))
        self.label_4.setText(_translate("Quinielas", "Edad"))
        self.label_5.setText(_translate("Quinielas", "Posicion"))
        self.label_31.setText(_translate("Quinielas", "Peso"))
        self.btnAgregarJugador.setText(_translate("Quinielas", "Agregar Jugador"))
        self.btneliminarjugador.setText(_translate("Quinielas", "Eliminar Jugador"))
        self.btnmodificarjugador.setText(_translate("Quinielas", "Modificar Jugador"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Jugador), _translate("Quinielas", "Jugador"))
        self.label_6.setText(_translate("Quinielas", "ID"))
        self.label_7.setText(_translate("Quinielas", "Nombre"))
        self.label_8.setText(_translate("Quinielas", "Apellido"))
        self.label_9.setText(_translate("Quinielas", "Edad"))
        self.label_32.setText(_translate("Quinielas", "Peso"))
        self.btnAgregarEntrenador.setText(_translate("Quinielas", "Agregar Entrenador"))
        self.btneliminarentrenador.setText(_translate("Quinielas", "Eliminar Entrenador"))
        self.btnmodificarentrenador.setText(_translate("Quinielas", "Modificar Entrenador"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Entrenador), _translate("Quinielas", "Entrenador"))
        self.label_11.setText(_translate("Quinielas", "Nombre"))
        self.label_12.setText(_translate("Quinielas", "Apellido"))
        self.label_13.setText(_translate("Quinielas", "Edad"))
        self.label_10.setText(_translate("Quinielas", "ID"))
        self.label_33.setText(_translate("Quinielas", "Peso"))
        self.label_41.setText(_translate("Quinielas", "Posicion"))
        self.btnAgregarArbitro.setText(_translate("Quinielas", "Agregar Arbitro"))
        self.btneliminararbitro.setText(_translate("Quinielas", "Eliminar Arbitro"))
        self.btnmodificararbitro.setText(_translate("Quinielas", "Modificar Arbitro"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Arbitro), _translate("Quinielas", "Arbitro"))
        self.label_14.setText(_translate("Quinielas", "ID Club"))
        self.label_19.setText(_translate("Quinielas", "Nombre del Club"))
        self.btnAgregarClub.setText(_translate("Quinielas", "Agregar Club"))
        self.btneliminarclub.setText(_translate("Quinielas", "Eliminar Club"))
        self.btnmodificarclub.setText(_translate("Quinielas", "Modificar Club"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Clubes), _translate("Quinielas", "Clubes"))
        self.label_15.setText(_translate("Quinielas", "ID"))
        self.label_16.setText(_translate("Quinielas", "Nombre del Equipo"))
        self.label_17.setText(_translate("Quinielas", "Jugadores"))
        self.label_18.setText(_translate("Quinielas", "Entrenador"))
        self.label_20.setText(_translate("Quinielas", "Club"))
        self.btnAgregarEquipo.setText(_translate("Quinielas", "Agregar Equipo"))
        self.btneliminarequipo.setText(_translate("Quinielas", "Eliminar Equipo"))
        self.btnmodificarequipo.setText(_translate("Quinielas", "Modificar Equipo"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Equipo), _translate("Quinielas", "Equipo"))
        self.label_21.setText(_translate("Quinielas", "Inicio de la Temporada"))
        self.label_22.setText(_translate("Quinielas", "Final de la Temporada"))
        self.btnAgregarTemporada.setText(_translate("Quinielas", "Agregar Temporada"))
        self.label_28.setText(_translate("Quinielas", "ID Temporada"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Temporada), _translate("Quinielas", "Temporada"))
        self.label_23.setText(_translate("Quinielas", "ID JORNADA"))
        self.label_24.setText(_translate("Quinielas", "FECHA JORNADA"))
        self.btnAgregarJornada.setText(_translate("Quinielas", "Agregar Jornada"))
        self.tabAgregar.setTabText(self.tabAgregar.indexOf(self.Jornadas), _translate("Quinielas", "Jornadas"))
        self.tabAgregarysupuestos.setTabText(self.tabAgregarysupuestos.indexOf(self.Agregar), _translate("Quinielas", "AGREGAR"))
        self.label_25.setText(_translate("Quinielas", "VS"))
        self.label_26.setText(_translate("Quinielas", "Equipo 1"))
        self.label_27.setText(_translate("Quinielas", "Equipo 2"))
        self.btnAgregarEncuentro.setText(_translate("Quinielas", "Agregar Encuentro"))
        self.label_29.setText(_translate("Quinielas", "Tipo de Encuentro"))
        self.tabEventos.setTabText(self.tabEventos.indexOf(self.Encuentro), _translate("Quinielas", "Encuentro"))
        self.label_30.setText(_translate("Quinielas", "Escoger Tipo"))
        self.label_34.setText(_translate("Quinielas", "Escoger Persona"))
        self.label_35.setText(_translate("Quinielas", "INTELECTUAL"))
        self.label_36.setText(_translate("Quinielas", "FÍSICO"))
        self.label_37.setText(_translate("Quinielas", "EMOCIONAL"))
        self.btnBiorritmo.setText(_translate("Quinielas", "Ver Biorritmo"))
        self.tabEventos.setTabText(self.tabEventos.indexOf(self.Biorritmos), _translate("Quinielas", "Biorritmos"))
        self.label_38.setText(_translate("Quinielas", "Temporada"))
        self.label_39.setText(_translate("Quinielas", "Jornada"))
        self.label_40.setText(_translate("Quinielas", "Encuentro"))
        self.btnhacerapuestas.setText(_translate("Quinielas", "Hacer Apuesta"))
        self.tabEventos.setTabText(self.tabEventos.indexOf(self.Quinielas), _translate("Quinielas", "Quinielas"))
        item = self.tablaresultados.horizontalHeaderItem(0)
        item.setText(_translate("Quinielas", "Equipo 1"))
        item = self.tablaresultados.horizontalHeaderItem(1)
        item.setText(_translate("Quinielas", "Equipo 2"))
        item = self.tablaresultados.horizontalHeaderItem(2)
        item.setText(_translate("Quinielas", "Resultado"))
        self.tabEventos.setTabText(self.tabEventos.indexOf(self.Historial), _translate("Quinielas", "Historial"))
        self.tabAgregarysupuestos.setTabText(self.tabAgregarysupuestos.indexOf(self.Supuestos), _translate("Quinielas", "SUPUESTOS"))
